{
 "title": "Lux Main Dashboard",
 "description": "Home dashboard with the most important indicators for your node and machine",
 "tags": [ "Lux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_network_node_uptime_weighted_average{job=\"luxd\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "gauge",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_network_node_uptime_rewarding_stake{job=\"luxd\"}",
     "legendFormat": "Rewarding stake {{node_id}}"
    }
   ]
  },
  {
   "title": "X Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_accepted_count{chain=\"X\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Accepted {{node_id}}"
    },
    {
     "expr": "round(increase(lux_snowman_blks_rejected_count{chain=\"X\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Rejected {{node_id}}"
    }
   ]
  },
  {
   "title": "Proposed X blocks",
   "type": "stat",
   "description": "Number of X-Chain blocks this node has proposed on the network in the last day.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_built{chain=\"X\", job=\"luxd\"}[1d]))",
     "legendFormat": "Proposed X blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_accepted_count{chain=\"P\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Accepted {{node_id}}"
    },
    {
     "expr": "round(increase(lux_snowman_blks_rejected_count{chain=\"P\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Rejected {{node_id}}"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_built{chain=\"P\", job=\"luxd\"}[1d]))",
     "legendFormat": "Proposed P blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"luxd-machine\", mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"luxd-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"luxd-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"luxd-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_health_checks_failing{check=\"health\",job=\"luxd\",tag=\"all\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lux_requests_average_latency", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of LUX currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_platformvm_total_staked{chain=\"P\", job=\"luxd\"}/1000000000",
     "legendFormat": "LUX {{node_id}}"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_stake_percent_connected{chain=\"P\", job=\"luxd\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lux_network_peers{job=\"luxd\"}",
     "legendFormat": "Peers {{node_id}}"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_accepted_count{chain=\"C\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Accepted {{node_id}}"
    },
    {
     "expr": "round(increase(lux_snowman_blks_rejected_count{chain=\"C\", job=\"luxd\"}[1m]))>0",
     "legendFormat": "Rejected {{node_id}}"
    }
   ]
  },
  {
   "title": "Proposed C blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the C-Chain in the last day.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_built{chain=\"C\", job=\"luxd\"}[1d]))",
     "legendFormat": "Built C blocks {{node_id}}"
    }
   ]
  },
  {
   "title": "Accepted Blocks",
   "type": "bargauge",
   "description": "Number of blocks accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(lux_snowman_blks_accepted_count{job=\"luxd\"}[1m]))",
     "legendFormat": "{{ chain }} Chain {{node_id}}"
    }
   ]
  },
  {
   "title": "Blocks processing",
   "type": "bargauge",
   "description": "Number of blocks currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_snowman_blks_processing{job=\"luxd\"}",
     "legendFormat": "{{ chain }} Chain {{node_id}}"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lux_benchlist_benched_num{job=\"luxd\"}",
     "legendFormat": "{{ chain }} Chain {{node_id}}"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "type": "math", "expression": "$A / ($A + $B)" }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(lux_meterdb_duration{chain=\"all\", job=\"luxd\"}[5m])/increase(lux_meterdb_calls{chain=\"all\", job=\"luxd\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  }
 ]
}